networks:
    ds-wordpress:
        driver: bridge


services:

    mysql:
        image: mysql:8.0
        container_name: ds-wordpress-mysql
        tty: true
        ports:
            - "4208:3306"
        volumes:
            - "./var/libclea/mysql/:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        networks:
            - ds-wordpress


    wordpress:
        image: wordpress:latest
        container_name: ds-wordpress
        ports:
            - "4282:80"
        volumes:
            - "./var/www/html/:/var/www/html"
        environment:
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_HOST: mysql
        depends_on:
            - mysql
        networks:
            - ds-wordpress


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ds-phpmyadmin
        ports:
            - "4283:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: wordpress
        depends_on:
            - mysql
        networks:
            - ds-wordpress